### ISSUE TITLE
SlidingFragmentActivity wrong height bounds

### ISSUE THREAD

**Issue by kobynet** [Cheesebaron/SlidingMenuSharp#6] opened 2013-09-11 14:48 UTC
When using SlidingFragmentActivity (including the sample, running on multiple phones/tablets) the content paint wrong, top is chopped.

![screenshot_2013-09-11-17-46-25](https://f.cloud.github.com/assets/618733/1123552/3e5e9370-1af1-11e3-8c3e-e38e7bb4f900.png)
![screenshot_2013-09-11-17-46-19](https://f.cloud.github.com/assets/618733/1123553/42cafba6-1af1-11e3-8ed9-4bcedeb43749.png)

**Comment by Cheesebaron** [comment] 2013-09-11 18:54
Duplicate of #1

**Closed as completed by Cheesebaron** 2013-09-11 18:54 UTC
